### ISSUE TITLE
not getting a matched txt file at all

### ISSUE THREAD

**Issue by Abellow101** [Ben-0-mad/YT-TMS-Finder#24]
also whats the max confidence of match?

**Comment by Ben-0-mad** [comment]
> also whats the max confidence of match?

The maximum number of matching fingerprints depends on the length of the songs in your database because longer songs induce more fingerprints. If you want an estimate for what's a good match. <20 matches means there's probably no match. About 30 matches means it could still be a possible match. 50 matches is a strong indication. >100 matches you can be sure that it is a match.
